### ISSUE TITLE
Updating existing elements

### ISSUE THREAD

**Issue by taye** [mjlescano/domator#1]
Thanks for writing and releasing domator. It's simply fantastic.

What do you think about allowing it to be used to update existing elements? For example:

```javascript
// a comment is created
var commentElement = d(`div#comment-${comment.id}.comment`, [
  `div.comment-author ${comment.author}`,
  `div.comment-date ${comment.date}`,
  `div.comment-content ${comment.content}`,
]);


// the same comment is edited
// update the div.comment element that was created earlier
d(commentElement, [
  // like `commentElement.querySelector('.comment-date') ...`
  `.comment-date`, [
    // querying this selector fails
    // -> append a new div.comment-edited to the .comment-date element
    `div.comment-edited ${newComment.editDate}`
  ],
  // update the comment text
  `.comment-content ${newComment.content}`,
  // the other elements are left unchanged
]);
```

**Comment by mjlescano** [comment]
hey @taye ! Really loved the idea :)
Got caught up reviewing it and ended up refactoring/updating a lot of stuff in the process :p

I realized that with your proposal can be confusing to work with lists, e.g.:
```javascript
var list = d('ul.list', ['li', 'li', 'li']) // creates an ul with 3 childs

// but, then: 

d(list, ['li']) // it does nothing, because the 'li' selector succeeds, and you would expect that "list" should have only 1 element now.
```

So, [here's](https://github.com/mjlescano/domator/pull/3) an option; when you pass an existant element, it removes all childrens and recreates them. What do you think?

**Comment by taye** [comment]
For my use case it's necessary to able to leave some child elements unchanged. How about using an empty `text` attribute to remove all children? I think it makes sense since setting `element.textContent` removes all of the element's child nodes for you.

```javascript
d(list, { text: '' }, ['li'])
```

It might be worth having a `Domator` "factory" function which takes an object with default attributes and returns a domator function which sets those attributes if the user doesn't. The module's default export could be `Domator({text:''})` so that the children are always cleared. For my case, I'd need to do something like this:

```javascript
import { Domator } from 'domator';
// or const Domator = require('domator/factory'); or something
const d = Domator({});

d(list, [
  // change this item's class
  'li.old-class', { className: 'new-class' },
  // replace the children of this item
  'li', { text: '' }, ['div'],
]);
```

**Comment by taye** [comment]
A virtual DOM library is what I really need.
